name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # CI server (runner) as ubuntu-latest

    steps:
      - name: Checkout # Checkout your code/files (Action checkout)
        uses: actions/checkout@v3

      - name: Configure AWS Credentials # - Configure access to AWS account (Action configure-aws-credentials)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform # - Terraform setup (Action?)
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 5.0"

      - name: Destroy Terraform
        run: terraform destroy -auto-approve

      - name: Print Message
        run: echo "Terraform destroyed. Hello from Destroy workflow!"
